package resetgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

var funcTpl = `// Generated by resetgen. DO NOT EDIT!

package {{ (index . 0).Pkg }}

{{- range $i, $s := . }}
{{- if not (eq (len $s.Fields) 0) }}
// Reset resets all fields of {{ $s.Name }}.
func (x *{{ $s.Name }}) Reset() {
	{{- range $f := $s.Fields }}
	{{- if $f.IsStruct }}
	if zer, ok := any(&x.{{ $f.Name }}).(interface{ Reset() }); ok {
		zer.Reset()
	} else {
		x.{{ $f.Name }} = {{ resetValue $f }}
	}
	{{- else if $f.IsMap }}
	clear(x.{{ $f.Name }})
	{{- else if $f.IsSlice}}
	x.{{ $f.Name }} = x.{{ resetValue $f }}
	{{- else if $f.IsPtr}}
	if x.{{ $f.Name }} != nil {
		*x.{{ $f.Name }} = {{ resetValue $f }}
	}	
	{{- else }}
	x.{{ $f.Name }} = {{ resetValue $f }}
	{{- end }}
	{{- end }}
}
{{- end }}
{{- end }}
`

var primitives = map[string]struct{}{
	"bool":   struct{}{},
	"string": struct{}{},
	"int":    struct{}{}, "int8": struct{}{}, "int16": struct{}{}, "int32": struct{}{}, "int64": struct{}{},
	"uint": struct{}{}, "uint8": struct{}{}, "uint16": struct{}{}, "uint32": struct{}{}, "uint64": struct{}{},
	"float32": struct{}{}, "float64": struct{}{},
	"byte": struct{}{}, "rune": struct{}{},
}

type structInfo struct {
	Pkg    string
	Name   string
	Fields []fieldInfo
}

type fieldInfo struct {
	Name        string
	typ         string
	IsEmbedded  bool
	IsStruct    bool
	IsPtr       bool
	IsPrimitive bool
	IsMap       bool
	IsSlice     bool
	IsArray     bool
}

func resetValue(fi fieldInfo) string {
	switch {
	case fi.IsPrimitive:
		switch fi.typ {
		case "bool":
			return "false"
		case "string":
			return "\"\""
		case "rune":
			return "'0'"
		default:
			return "0"
		}
	case fi.IsSlice:
		return fi.Name + "[:0]"
	case fi.IsArray:
		return fi.typ + "{}"
	case fi.IsMap:
		return "clear(" + fi.Name + ")"
	default:
		return fi.typ + "{}"
	}
}

func (fi *fieldInfo) setType(expr ast.Expr) {
	switch typed := expr.(type) {
	case (*ast.StarExpr):
		fi.IsPtr = true
		fi.typ = strings.TrimPrefix(fi.typ, "*")
		fi.setType(typed.X)
	case (*ast.ArrayType):
		if typed.Len != nil {
			fi.IsArray = true
		}
		fi.IsSlice = !fi.IsArray
	case (*ast.MapType):
		fi.IsMap = true
	case (*ast.SelectorExpr):
		fi.IsStruct = true
	case (*ast.Ident):
		if _, ok := primitives[fi.typ]; ok {
			fi.IsPrimitive = true
		}
		fi.IsStruct = !fi.IsPrimitive
	}
}

type pkgInfo struct {
	name       string
	path       string
	outputPath string
	structs    []structInfo
}

type generator struct {
	pkgs         map[string]pkgInfo
	skipSuffixes []string
	skipPaths    []string
}

func new(skipSuffixes []string, skipPaths []string) generator {
	return generator{
		pkgs:         make(map[string]pkgInfo),
		skipSuffixes: skipSuffixes,
		skipPaths:    skipPaths,
	}
}

func (g *generator) scanDir(root string) error {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("error resolving root path: %w", err)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedImports,
		Dir:  absRoot,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return fmt.Errorf("error loading packages: %w", err)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}

		if err := g.scanPackage(pkg); err != nil {
			return fmt.Errorf("error scanning package %s: %w", pkg.PkgPath, err)
		}
	}

	return nil
}

func (g *generator) scanPackage(pkg *packages.Package) error {
	pkgInfo := pkgInfo{
		name:       pkg.Name,
		path:       pkg.PkgPath,
		outputPath: filepath.Join(pkg.Dir, pkg.Name+".gen.go"),
		structs:    []structInfo{},
	}

fileLoop:
	for _, file := range pkg.GoFiles {
		for _, suf := range g.skipSuffixes {
			if strings.HasSuffix(file, suf) {
				continue fileLoop
			}
		}

		for _, path := range g.skipPaths {
			if strings.HasPrefix(file, path) {
				continue fileLoop
			}
		}

		var syntax *ast.File
		for _, f := range pkg.Syntax {
			filePtr := pkg.Fset.File(f.Pos())
			if filePtr == nil {
				continue
			}
			if filepath.Clean(filePtr.Name()) == filepath.Clean(file) {
				syntax = f
				break
			}
		}
		if syntax == nil {
			continue
		}

		structs := g.scanFile(syntax)
		pkgInfo.structs = append(pkgInfo.structs, structs...)
	}

	if len(pkgInfo.structs) > 0 {
		g.pkgs[pkgInfo.path] = pkgInfo
	}

	return nil
}

func checkComment(comments *ast.CommentGroup) bool {
	if comments == nil {
		return false
	}

	for _, line := range comments.List {
		if strings.TrimSpace(line.Text) == "// generate:reset" {
			return true
		}
	}

	return false
}

func (g *generator) scanFile(f *ast.File) []structInfo {
	var structs []structInfo
	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			if !checkComment(genDecl.Doc) {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			if structType.Fields == nil {
				continue
			}

			fields := []fieldInfo{}

			for _, fieldGroup := range structType.Fields.List {
				var buf bytes.Buffer
				err := format.Node(&buf, token.NewFileSet(), fieldGroup.Type)
				if err != nil {
					continue
				}
				groupType := buf.String()

				if len(fieldGroup.Names) == 0 {
					f := fieldInfo{
						Name: groupType,
						typ:  groupType,
					}
					f.setType(fieldGroup.Type)
					fields = append(fields, f)
					continue
				}

				for _, field := range fieldGroup.Names {
					f := fieldInfo{
						Name: field.Name,
						typ:  groupType,
					}
					f.setType(fieldGroup.Type)
					fields = append(fields, f)
				}
			}

			structs = append(structs, structInfo{
				Pkg:    f.Name.Name,
				Name:   typeSpec.Name.Name,
				Fields: fields,
			})
		}
	}
	return structs
}

// Do generates the code.
func Do(root string, skipSuffixes, skipPaths []string) error {
	g := new(skipSuffixes, skipPaths)
	err := g.scanDir(root)
	if err != nil {
		return fmt.Errorf("error scanning for structs: %w", err)
	}

	if len(g.pkgs) == 0 {
		return nil
	}

	for _, pkg := range g.pkgs {
		if len(pkg.structs) == 0 {
			continue
		}

		if err := g.generatePackage(pkg); err != nil {
			return fmt.Errorf("error generating for package %s: %w", pkg.path, err)
		}
	}
	return nil
}

func (g *generator) generatePackage(pkg pkgInfo) error {
	tmpl := template.Must(template.New("reset").Funcs(template.FuncMap{
		"resetValue": resetValue,
	}).Parse(funcTpl))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, pkg.structs); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting generated code: %w", err)
	}

	return os.WriteFile(pkg.outputPath, formatted, 0644)
}
