// Code generated by MockGen. DO NOT EDIT.
// Source: ./handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/ashershnyov/go-metrics-gatherer/internal/server/model"
	gomock "github.com/golang/mock/gomock"
)

// MockmetricService is a mock of metricService interface.
type MockmetricService struct {
	ctrl     *gomock.Controller
	recorder *MockmetricServiceMockRecorder
}

// MockmetricServiceMockRecorder is the mock recorder for MockmetricService.
type MockmetricServiceMockRecorder struct {
	mock *MockmetricService
}

// NewMockmetricService creates a new mock instance.
func NewMockmetricService(ctrl *gomock.Controller) *MockmetricService {
	mock := &MockmetricService{ctrl: ctrl}
	mock.recorder = &MockmetricServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetricService) EXPECT() *MockmetricServiceMockRecorder {
	return m.recorder
}

// GetMetric mocks base method.
func (m *MockmetricService) GetMetric(ctx context.Context, name string, typ model.MetricType) (model.InternalMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", ctx, name, typ)
	ret0, _ := ret[0].(model.InternalMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockmetricServiceMockRecorder) GetMetric(ctx, name, typ interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockmetricService)(nil).GetMetric), ctx, name, typ)
}

// ListMetrics mocks base method.
func (m *MockmetricService) ListMetrics(ctx context.Context) ([]model.InternalMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetrics", ctx)
	ret0, _ := ret[0].([]model.InternalMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetrics indicates an expected call of ListMetrics.
func (mr *MockmetricServiceMockRecorder) ListMetrics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetrics", reflect.TypeOf((*MockmetricService)(nil).ListMetrics), ctx)
}

// UpdateMetric mocks base method.
func (m *MockmetricService) UpdateMetric(ctx context.Context, metric model.InternalMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetric", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetric indicates an expected call of UpdateMetric.
func (mr *MockmetricServiceMockRecorder) UpdateMetric(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetric", reflect.TypeOf((*MockmetricService)(nil).UpdateMetric), ctx, metric)
}

// UpdateMultipleMetrics mocks base method.
func (m *MockmetricService) UpdateMultipleMetrics(ctx context.Context, metrics []model.InternalMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMultipleMetrics", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMultipleMetrics indicates an expected call of UpdateMultipleMetrics.
func (mr *MockmetricServiceMockRecorder) UpdateMultipleMetrics(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMultipleMetrics", reflect.TypeOf((*MockmetricService)(nil).UpdateMultipleMetrics), ctx, metrics)
}

// MockauditLogger is a mock of auditLogger interface.
type MockauditLogger struct {
	ctrl     *gomock.Controller
	recorder *MockauditLoggerMockRecorder
}

// MockauditLoggerMockRecorder is the mock recorder for MockauditLogger.
type MockauditLoggerMockRecorder struct {
	mock *MockauditLogger
}

// NewMockauditLogger creates a new mock instance.
func NewMockauditLogger(ctrl *gomock.Controller) *MockauditLogger {
	mock := &MockauditLogger{ctrl: ctrl}
	mock.recorder = &MockauditLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauditLogger) EXPECT() *MockauditLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockauditLogger) Log(arg0 context.Context, arg1 []string, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockauditLoggerMockRecorder) Log(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockauditLogger)(nil).Log), arg0, arg1, arg2)
}
